# Generated by Django 5.0.3 on 2024-03-11 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=250, null=True, verbose_name='место выполнения привычки')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время выполнения')),
                ('action', models.CharField(max_length=500, verbose_name='выполняемое действие')),
                ('pleasant_habit', models.BooleanField(verbose_name='признак приятной привычки')),
                ('periodicity', models.IntegerField(verbose_name='периодичность выполнения привычки')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.IntegerField(verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности привычки')),
                ('date', models.DateField(verbose_name='дата последнего выполнения привычки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habit.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ['action'],
            },
        ),
    ]
