# Generated by Django 5.0.3 on 2024-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='дата последнего выполнения привычки'),
        ),
    ]
