# Generated by Django 4.2 on 2024-03-18 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='date',
        ),
        migrations.AddField(
            model_name='habit',
            name='date_habit',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 18), null=True, verbose_name='дата последнего выполнения привычки'),
        ),
    ]
