# Generated by Django 4.2 on 2024-03-21 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_remove_habit_date_habit_date_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='date_habit',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='дата последнего выполнения привычки'),
        ),
    ]
